import type { Config } from "tailwindcss"

const config: Config = {
  theme: {
    extend: {
      typography: {
        DEFAULT: {
          css: {
            "--tw-prose-body": "var(--ui-text-secondary)",
            "--tw-prose-headings": "var(--ui-text)",
            "--tw-prose-links": "var(--ui-text)",
            "--tw-prose-bold": "var(--ui-text)",
            "--tw-prose-counters": "var(--ui-text-muted)",
            "--tw-prose-bullets": "var(--ui-text-muted)",
            "--tw-prose-hr": "var(--ui-border)",
            "--tw-prose-quotes": "var(--ui-text-secondary)",
            "--tw-prose-quote-borders": "var(--ui-border)",
            "--tw-prose-captions": "var(--ui-text-muted)",
            "--tw-prose-kbd": "var(--ui-text)",
            "--tw-prose-code": "var(--ui-text)",
            "--tw-prose-pre-code": "var(--ui-text)",
            "--tw-prose-pre-bg": "var(--ui-bg-soft)",
            "--tw-prose-th-borders": "var(--ui-border)",
            "--tw-prose-td-borders": "var(--ui-border)",
            fontFamily: "var(--font-sans)",
            fontSize: "16px",
            lineHeight: "1.95",
            overflowWrap: "anywhere",
            "h1, h2, h3, h4": {
              fontFamily: "var(--font-sans)",
              fontWeight: "500",
              letterSpacing: "0.02em",
              scrollMarginTop: "24px",
              textWrap: "pretty",
            },
            h1: { fontSize: "28px", lineHeight: "1.6" },
            h2: {
              fontSize: "22px",
              lineHeight: "1.65",
              marginTop: "32px",
              marginBottom: "14px",
            },
            h3: { fontSize: "18px", lineHeight: "1.75" },
            h4: { fontSize: "16px", lineHeight: "1.8" },
            p: { marginTop: "22px", marginBottom: "22px" },
            a: {
              fontWeight: "400",
              textDecorationColor: "var(--ui-text-muted)",
              textUnderlineOffset: "4px",
              "&:hover": { color: "var(--ui-text)", textDecorationColor: "currentColor" },
            },
            strong: { fontWeight: "600" },
            blockquote: {
              padding: "12px 18px",
              borderInlineStartWidth: "2px",
              backgroundColor: "var(--ui-bg-soft)",
              fontStyle: "normal",
              fontWeight: "400",
              "p:first-of-type::before": { content: "none" },
              "p:last-of-type::after": { content: "none" },
            },
            code: {
              padding: "1px 4px",
              border: "1px solid var(--ui-border)",
              borderRadius: "3px",
              backgroundColor: "var(--ui-bg-soft)",
              fontFamily: "var(--font-mono)",
              fontWeight: "400",
              fontSize: "0.88em",
              overflowWrap: "anywhere",
              "&::before": { display: "none" },
              "&::after": { display: "none" },
            },
            pre: {
              maxWidth: "100%",
              overflowX: "auto",
              padding: "16px",
              border: "1px solid var(--ui-border)",
              borderRadius: "6px",
              fontFamily: "var(--font-mono)",
              fontSize: "13px",
              lineHeight: "1.85",
              letterSpacing: "0",
              whiteSpace: "pre",
              overflowWrap: "normal",
              code: {
                padding: "0",
                border: "0",
                borderRadius: "0",
                backgroundColor: "transparent",
                fontSize: "inherit",
                lineHeight: "inherit",
                whiteSpace: "inherit",
                overflowWrap: "normal",
              },
            },
            table: {
              display: "block",
              width: "100%",
              maxWidth: "100%",
              overflowX: "auto",
              fontSize: "14px",
              lineHeight: "1.75",
              borderCollapse: "collapse",
              textAlign: "start",
              overflowWrap: "normal",
            },
            "th, td": {
              minWidth: "120px",
              padding: "10px 14px",
              verticalAlign: "top",
            },
            th: { fontWeight: "500", backgroundColor: "var(--ui-bg-soft)" },
            "tbody tr:nth-child(even)": { backgroundColor: "var(--ui-bg-soft)" },
            img: {
              maxWidth: "100%",
              height: "auto",
              borderRadius: "4px",
            },
            "video, iframe": { maxWidth: "100%" },
            figcaption: { fontSize: "12px", lineHeight: "1.8", textAlign: "center" },
            kbd: {
              padding: "2px 5px",
              border: "1px solid var(--ui-border)",
              borderRadius: "3px",
              backgroundColor: "var(--ui-bg-soft)",
              boxShadow: "none",
              fontFamily: "var(--font-mono)",
              fontWeight: "400",
            },
            mark: { color: "var(--ui-text)", backgroundColor: "var(--ui-bg-soft)" },
            hr: { marginTop: "32px", marginBottom: "32px" },
          },
        },
      },
    },
  },
}

export default config
